from __future__ import print_function

# -*- coding: utf-8 -*-
"""vgg16_nst.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SAaNvV-E3nBCk30OeQJAuPmkzThPcl-z
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

# from google.colab import drive
# drive.mount('/content/drive')

"""Neural Transfer Using PyTorch
=============================

# Importing Packages and Selecting a Device
"""


import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from PIL import Image
import matplotlib.pyplot as plt

import torchvision.transforms as transforms
import torchvision.models as models

import copy

import time

# !nvidia-smi

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

"""# Loading the Images

"""

# cd /content/drive/MyDrive/1085 Cloud Computing and ML/hws/proj2/Leon2015/images/

# desired size of the output image
imsize = 512 if torch.cuda.is_available() else 128  # use small size if no gpu

loader = transforms.Compose([
    transforms.Resize(imsize),  # scale imported image
    transforms.ToTensor()])  # transform it into a torch tensor


def image_loader(image_name):
    image = Image.open(image_name)
    # fake batch dimension required to fit network's input dimensions
    image = loader(image).unsqueeze(0)
    return image.to(device, torch.float)


style_img = image_loader("./images/picasso.jpg")
style2_img = image_loader("./images/style.jpeg")
content_img = image_loader("./images/dancing.jpg")
nyu_img = image_loader("./images/input.jpg")
self_img = image_loader("./images/selfie.JPG")
mz_img = image_loader('./images/mz.jpeg')


assert style_img.size() == content_img.size(), \
    "we need to import style and content images of the same size"

class ContentLoss(nn.Module):

    def __init__(self, target,):
        super(ContentLoss, self).__init__()
        # we 'detach' the target content from the tree used
        # to dynamically compute the gradient: this is a stated value,
        # not a variable. Otherwise the forward method of the criterion
        # will throw an error.
        self.target = target.detach()

    def forward(self, input):
        self.loss = F.mse_loss(input, self.target)
        return input

def gram_matrix(input):
    a, b, c, d = input.size()  # a=batch size(=1)
    # b=number of feature maps
    # (c,d)=dimensions of a f. map (N=c*d)

    features = input.view(a * b, c * d)  # resise F_XL into \hat F_XL

    G = torch.mm(features, features.t())  # compute the gram product

    # we 'normalize' the values of the gram matrix
    # by dividing by the number of element in each feature maps.
    return G.div(a * b * c * d)

class StyleLoss(nn.Module):

    def __init__(self, target_feature):
        super(StyleLoss, self).__init__()
        self.target = gram_matrix(target_feature).detach()

    def forward(self, input):
        G = gram_matrix(input)
        self.loss = F.mse_loss(G, self.target)
        return input

"""# Importing the Model



"""

cnn = models.vgg19(pretrained=True).features.to(device).eval()

# cnn

cnn_normalization_mean = torch.tensor([0.485, 0.456, 0.406]).to(device)
cnn_normalization_std = torch.tensor([0.229, 0.224, 0.225]).to(device)

# create a module to normalize input image so we can easily put it in a
# nn.Sequential
class Normalization(nn.Module):
    def __init__(self, mean, std):
        super(Normalization, self).__init__()
        # .view the mean and std to make them [C x 1 x 1] so that they can
        # directly work with image Tensor of shape [B x C x H x W].
        # B is batch size. C is number of channels. H is height and W is width.
        # self.mean = torch.tensor(mean).view(-1, 1, 1)
        self.mean = mean.view(-1, 1, 1)
        # self.std = torch.tensor(std).view(-1, 1, 1)
        self.std = std.view(-1, 1, 1)

    def forward(self, img):
        # normalize img
        return (img - self.mean) / self.std

# desired depth layers to compute style/content losses :
content_layers_default = ['conv_4']
style_layers_default = ['conv_1', 'conv_2', 'conv_3', 'conv_4', 'conv_5']

def get_style_model_and_losses(cnn, normalization_mean, normalization_std,
                               style_img, content_img,
                               content_layers=content_layers_default,
                               style_layers=style_layers_default):
    cnn = copy.deepcopy(cnn)

    # normalization module
    normalization = Normalization(normalization_mean, normalization_std).to(device)

    # just in order to have an iterable access to or list of content/syle
    # losses
    content_losses = []
    style_losses = []

    # assuming that cnn is a nn.Sequential, so we make a new nn.Sequential
    # to put in modules that are supposed to be activated sequentially
    model = nn.Sequential(normalization)

    i = 0  # increment every time we see a conv
    for layer in cnn.children():
        if isinstance(layer, nn.Conv2d):
            i += 1
            name = 'conv_{}'.format(i)
        elif isinstance(layer, nn.ReLU):
            name = 'relu_{}'.format(i)
            # The in-place version doesn't play very nicely with the ContentLoss
            # and StyleLoss we insert below. So we replace with out-of-place
            # ones here.
            layer = nn.ReLU(inplace=False)
        elif isinstance(layer, nn.MaxPool2d):
            name = 'pool_{}'.format(i)
        elif isinstance(layer, nn.BatchNorm2d):
            name = 'bn_{}'.format(i)
        else:
            raise RuntimeError('Unrecognized layer: {}'.format(layer.__class__.__name__))

        model.add_module(name, layer)

        if name in content_layers:
            # add content loss:
            target = model(content_img).detach()
            content_loss = ContentLoss(target)
            model.add_module("content_loss_{}".format(i), content_loss)
            content_losses.append(content_loss)

        if name in style_layers:
            # add style loss:
            target_feature = model(style_img).detach()
            style_loss = StyleLoss(target_feature)
            model.add_module("style_loss_{}".format(i), style_loss)
            style_losses.append(style_loss)

    # now we trim off the layers after the last content and style losses
    for i in range(len(model) - 1, -1, -1):
        if isinstance(model[i], ContentLoss) or isinstance(model[i], StyleLoss):
            break

    model = model[:(i + 1)]

    return model, style_losses, content_losses

"""# Gradient Descent



"""

def get_input_optimizer(input_img):
    # this line to show that input is a parameter that requires a gradient
    optimizer = optim.LBFGS([input_img.requires_grad_()])
    return optimizer

def run_style_transfer(cnn, normalization_mean, normalization_std,
                       content_img, style_img, input_img, num_steps=300,
                       style_weight=1000000, content_weight=1):
    """Run the style transfer."""
    print('Building the style transfer model..')
    model, style_losses, content_losses = get_style_model_and_losses(cnn,
        normalization_mean, normalization_std, style_img, content_img)
    optimizer = get_input_optimizer(input_img)

    print('Optimizing..')
    run = [0]
    while run[0] <= num_steps:

        def closure():
            # correct the values of updated input image
            input_img.data.clamp_(0, 1)

            optimizer.zero_grad()
            model(input_img)
            style_score = 0
            content_score = 0

            for sl in style_losses:
                style_score += sl.loss
            for cl in content_losses:
                content_score += cl.loss

            style_score *= style_weight
            content_score *= content_weight

            loss = style_score + content_score
            loss.backward()

            run[0] += 1
            if run[0] % 50 == 0:
                print("run {}:".format(run))
                print('Style Loss : {:4f} Content Loss: {:4f}'.format(
                    style_score.item(), content_score.item()))
                print()

            return style_score + content_score

        optimizer.step(closure)

    # a last correction...
    input_img.data.clamp_(0, 1)

    return input_img

unloader = transforms.ToPILImage()  # reconvert into PIL image

plt.ion()

def imshow(tensor, title=None):
    image = tensor.cpu().clone()  # we clone the tensor to not do changes on it
    image = image.squeeze(0)      # remove the fake batch dimension
    image = unloader(image)
    plt.imshow(image)
    if title is not None:
        plt.title(title)
    plt.pause(0.001) # pause a bit so that plots are updated

def plot_output(c1_im, c1_s1_output, s1_im):
    f, axarr = plt.subplots(nrows=1,ncols=3)
    f.set_figwidth(15)
    plt.sca(axarr[0]); 
    plt.imshow(c1_im.cpu().detach().permute(0,2,3,1).numpy()[0]); plt.title('Input Image')
    plt.sca(axarr[1]); 
    plt.imshow(c1_s1_output.cpu().detach().permute(0,2,3,1).numpy()[0]); plt.title('Output Image')
    plt.sca(axarr[2]); 
    plt.imshow(s1_im.cpu().detach().permute(0,2,3,1).numpy()[0]); plt.title('Style Image')
    plt.ioff()
    plt.show()

"""# Live demo"""

plt.figure()
imshow(style_img, title='Style Image1')

plt.figure()
imshow(style2_img, title='Style Image2')

plt.figure()
imshow(nyu_img, title='Content Image')

plt.figure()
imshow(self_img, title='Content2 Image')

plt.figure()
imshow(mz_img, title='Content3 Image')

# newsize = (1, 3, 128, 128)
# nyu_img = nyu_img.resize(newsize)
# print(nyu_img.shape, content_img.shape, style_img.shape)

print(nyu_img[:,:,:,:512].shape, content_img.shape, style_img.shape)
print(nyu_img[:,:,:,:512].shape, content_img.shape, style2_img[:,:,:512,:].shape)

print(self_img[:,:,:512,:512].shape, content_img.shape, style_img.shape)
print(self_img[:,:,:512,:512].shape, content_img.shape, style2_img[:,:,:512,:].shape)
print(self_img[:,:,:512,:512].shape, content_img.shape, style_img.shape)
print(self_img[:,:,:512,:512].shape, content_img.shape, style2_img[:,:,:512,:].shape)

c1_im = nyu_img[:,:,:,:512].clone()
c2_im = self_img[:,:,:512,:512].clone()
c3_im = mz_img[:,:,:512,:512].clone()

s1_im = style_img.clone()
s2_im = style2_img[:,:,:512,:].clone()

time.time()

start_time = time.time()
# c1_s1_output = run_style_transfer(cnn, cnn_normalization_mean, cnn_normalization_std,
                            # c1_im.clone(), s1_im.clone(), c1_im.clone())
t1 = time.time() - start_time

start_time = time.time()
c2_s1_output = run_style_transfer(cnn, cnn_normalization_mean, cnn_normalization_std,
                            c2_im.clone(), s1_im.clone(), c2_im.clone())
t2 = time.time() - start_time

start_time = time.time()
c3_s1_output = run_style_transfer(cnn, cnn_normalization_mean, cnn_normalization_std,
                            c3_im.clone(), s1_im.clone(), c3_im.clone())
t3 = time.time() - start_time

start_time = time.time()
c1_s2_output = run_style_transfer(cnn, cnn_normalization_mean, cnn_normalization_std,
                            c1_im.clone(), s2_im.clone(), c1_im.clone())
t4 = time.time() - start_time

start_time = time.time()
c2_s2_output = run_style_transfer(cnn, cnn_normalization_mean, cnn_normalization_std,
                            c2_im.clone(), s2_im.clone(), c2_im.clone())
t5 = time.time() - start_time

start_time = time.time()
c3_s2_output = run_style_transfer(cnn, cnn_normalization_mean, cnn_normalization_std,
                            c3_im.clone(), s2_im.clone(), c3_im.clone())
t6 = time.time() - start_time

# plot_output(c1_im, c1_s1_output, s1_im)

plot_output(c1_im, c1_s2_output, s2_im)

plot_output(c2_im, c2_s1_output, s1_im)

plot_output(c2_im, c2_s2_output, s2_im)

plot_output(c3_im, c3_s1_output, s1_im)

plot_output(c3_im, c3_s2_output, s2_im)

"""# Get Experiment Data

## training time
"""

print(t1,t2,t3,t4,t5,t6)

print((t1+t2+t3+t4+t5+t6)/6)

"""## Params"""

# trainable params
trainable_pytorch_total_params = sum(p.numel() for p in cnn.parameters() if p.requires_grad)
print(trainable_pytorch_total_params)

# all params
pytorch_total_params = sum(p.numel() for p in cnn.parameters())
print(pytorch_total_params)

